# Файл docker-compose должен начинаться с тега версии.
version: "3"
# Раздел, в котором будут описаны сервисы, начинается с 'services'
services:
#Имя сервиса
  dvdocker:
    # Ключевое слово "build" позволяет задать путь к файлу Dockerfile, который нужно использовать для создания образа,
    build: DC/
    # Команда, которую нужно запустить после создания образа.
    command: bash ./datetime.sh